-- Add privacy flags to users table
ALTER TABLE public.users 
ADD COLUMN IF NOT EXISTS show_bio BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS show_phone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS show_socials BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS hide_avatar BOOLEAN DEFAULT FALSE;
